AttrDict = { 
    #Base attributes 
        'HUC_12': 'Twelve Digit Hydrologic Unit Code. This field provides a unique 12-digit code for each subwatershed. Numbers were assigned in an upstream to downstream fashion. Where no downstream/upstream relationship could be determined, numbers were assigned in a clockwise fashion.',    #land Cover on Slope Proportions
        'NI_SL_A': 'The area of the rasterized reporting unit occupied by All Natural Land Use on slopes that are are equal to or exceed the {slope} Slope threshold.', 
        'wtr_SL_A': 'The area of the rasterized reporting unit occupied by Water on slopes that are are equal to or exceed the {slope} Slope threshold', 
        'bar_SL_A': 'The area of the rasterized reporting unit occupied by Barren on slopes that are are equal to or exceed the {slope} Slope threshold.', 
        'for_SL_A': 'The area of the rasterized reporting unit occupied by Forest on slopes that are are equal to or exceed the {slope} Slope threshold.',
        'tun_SL_A': 'The area of the rasterized reporting unit occupied by Tundra on slopes that are are equal to or exceed the {slope} Slope threshold.', 
        'shb_SL_A': 'The area of the rasterized reporting unit occupied by Shrub on slopes that are are equal to or exceed the {slope} Slope threshold.',
        'hrb_SL_A': 'The area of the rasterized reporting unit occupied by Herbaceous on slopes that are are equal to or exceed the {slope} Slope threshold.', 
        'wtl_SL_A': 'The area of the rasterized reporting unit occupied by Wetland on slopes that are are equal to or exceed the {slope} Slope threshold.',
        'wtlw_SL_A': 'The area of the rasterized reporting unit occupied by Woody Wetland on slopes that are are equal to or exceed the {slope} Slope threshold.',
        'wtle_SL_A': 'The area of the rasterized reporting unit occupied by Emergent Wetland on slopes that are are equal to or exceed the {slope} Slope threshold.',
        'UI_SL_A': 'The area of the rasterized reporting unit occupied by All Human Land Use on slopes that are are equal to or exceed the {slope} Slope threshold.',
        'dev_SL_A': 'The area of the rasterized reporting unit occupied by Developed on slopes that are are equal to or exceed the {slope} Slope threshold.', 
        'devo_SL_A': 'The area of the rasterized reporting unit occupied by Open Space Developed on slopes that are are equal to or exceed the {slope} Slope threshold.', 
        'devl_SL_A': 'The area of the rasterized reporting unit occupied by Low Intensity Developed on slopes that are are equal to or exceed the {slope} Slope threshold.', 
        'devm_SL_A': 'The area of the rasterized reporting unit occupied by Medium Intensity Developed on slopes that are are equal to or exceed the {slope} Slope threshold.', 
        'devh_SL_A': 'The area of the rasterized reporting unit occupied by High Intensity Developed on slopes that are are equal to or exceed the {slope} Slope threshold.', 
        'agr_SL_A': 'The area of the rasterized reporting unit occupied by Agriculture on slopes that are are equal to or exceed the {slope} Slope threshold.',
        'agrp_SL_A': 'The area of the rasterized reporting unit occupied by Pasture/Hay on slopes that are are equal to or exceed the {slope} Slope threshold.', 
        'agrc_SL_A': 'The area of the rasterized reporting unit occupied by Cultivated Crop on slopes that are are equal to or exceed the {slope} Slope threshold.',

        'NI_SL': 'The percent of the reporting unit occupied by All Natural Land Use on slopes that are equal to or exceed the {slope} slope threshold.', 
        'wtr_SL': 'The percent of the reporting unit occupied by Water on slopes that are equal to or exceed the {slope} slope threshold.', 
        'bar_SL': 'The percent of the reporting unit occupied by Barren on slopes that are equal to or exceed the {slope} slope threshold.', 
        'for_SL': 'The percent of the reporting unit occupied by Forest on slopes that are equal to or exceed the {slope} slope threshold.',
        'tun_SL': 'The percent of the reporting unit occupied by Tundra on slopes that are equal to or exceed the {slope} slope threshold.', 
        'shb_SL': 'The percent of the reporting unit occupied by Shrub on slopes that are equal to or exceed the {slope} slope threshold.',
        'hrb_SL': 'The percent of the reporting unit occupied by Herbaceous on slopes that are equal to or exceed the {slope} slope threshold.', 
        'wtl_SL': 'The percent of the reporting unit occupied by Wetland on slopes that are equal to or exceed the {slope} slope threshold.',
        'wtlw_SL': 'The percent of the reporting unit occupied by Woody Wetland on slopes that are equal to or exceed the {slope} slope threshold.',
        'wtle_SL': 'The percent of the reporting unit occupied by Emergent Wetland on slopes that are equal to or exceed the {slope} slope threshold.',
        'UI_SL': 'The percent of the reporting unit occupied by All Human Land Use on slopes that are equal to or exceed the {slope} slope threshold.',
        'dev_SL': 'The percent of the reporting unit occupied by Developed on slopes that are equal to or exceed the {slope} slope threshold.', 
        'devo_SL': 'The percent of the reporting unit occupied by Open Space Developed on slopes that are equal to or exceed the {slope} slope threshold.', 
        'devl_SL': 'The percent of the reporting unit occupied by Low Intensity Developed on slopes that are equal to or exceed the {slope} slope threshold.', 
        'devm_SL': 'The percent of the reporting unit occupied by Medium Intensity Developed on slopes that are equal to or exceed the {slope} slope threshold.', 
        'devh_SL': 'The percent of the reporting unit occupied by High Intensity Developed on slopes that are equal to or exceed the {slope} slope threshold.', 
        'agr_SL': 'The percent of the reporting unit occupied by Agriculture on slopes that are equal to or exceed the {slope} slope threshold.',
        'agrp_SL': 'The percent of the reporting unit occupied by Pasture/Hay on slopes that are equal to or exceed the {slope} slope threshold.', 
        'agrc_SL': 'The percent of the reporting unit occupied by Cultivated Crop on slopes that are equal to or exceed the {slope} slope threshold.',
   
    #Riparian Land Cover Proportions
        'rNI': 'All Natural Land Use using a {dist} buffer',
        'rwtr': 'Water using a {dist} buffer', 
        'rbar': 'Barren using a {dist} buffer', 
        'rfor': 'Forest using a {dist} buffer',
        'rtun': 'Tundra using a {dist} buffer',
        'rshb': 'Shrubland using a {dist} buffer',
        'rhrb': 'Herbaceous using a {dist} buffer',
        'rwtl': 'Wetland using a {dist} buffer', 
        'rwtlw' : 'Woody Wetland using a {dist} buffer', 
        'rwtle': 'Emergent Wetland using a {dist} buffer',
        'rUI': 'All Human Land Use using a {dist} buffer',
        'rdev': 'Developed using a {dist} buffer',
        'rdevo': 'Open Space Developed using a {dist} buffer',
        'rdevl': 'Low Intensity Developed using a {dist} buffer',
        'rdevm': 'Medium Intensity Developed using a {dist} buffer',
        'rdevh': 'High Intensity Developed using a {dist} buffer', 
        'ragr': 'Agriculture using a {dist} buffer', 
        'ragrp': 'Pasture/Hay using a {dist} buffer',
        'ragrc': 'Cultivated Crop using a {dist} buffer',

    #Stream Density Metrics      
        'Shape_Length': 'Reporting Unit Shape Length', 
        'Shape_Area': 'Reporting Unit Shape Area', 
        'AREAKM2': 'The area of the reporting unit in km^2', 
        'STRMKM': 'The total length of Stream feature lines in km within the reporting unit.', 
        'STRMDENS': 'The density of Stream feature lines in km/km^2 within the reporting unit.',
        'STRMDENS0': 'The density of 0 Order Stream feature lines in km/km^2 within the reporting unit.', 
        'STRMDENS1': 'The density of 1st Order Stream feature lines in km/km^2 within the reporting unit.', 
        'STRMDENS2': 'The density of 2nd Order Stream feature lines in km/km^2 within the reporting unit',
        'STRMDENS3': 'The density of 3rd Order Stream feature lines in km/km^2 within the reporting unit.', 
        'STRMDENS4': 'The density of 4th Order Stream feature lines in km/km^2 within the reporting unit.',
        'STRMDENS5': 'The density of 5th Order Stream feature lines in km/km^2 within the reporting unit.',
        'STRMDENS6': 'The density of 6th Order Stream feature lines in km/km^2 within the reporting unit.',
        'STRMDENS7': 'The density of 7th Order Stream feature lines in km/km^2 within the reporting unit.', 
        'STRMDENS8': 'The density of 8th Order Stream feature lines in km/km^2 within the reporting unit.',
        'STRMDENS9': 'The density of 9th Order Stream feature lines in km/km^2 within the reporting unit.',
        
        'STRMKM0': 'The total length of 0 Order Stream feature lines in km within the reporting unit.',
        'STRMKM1': 'The total length of 1st Order Stream feature lines in km within the reporting unit.',
        'STRMKM2': 'The total length of 2nd Order Stream feature lines in km within the reporting unit.',
        'STRMKM3': 'The total length of 3rd Order Stream feature lines in km within the reporting unit.',
        'STRMKM4': 'The total length of 4th Order Stream feature lines in km within the reporting unit.',
        'STRMKM5': 'The total length of 5th Order Stream feature lines in km within the reporting unit.',
        'STRMKM6': 'The total length of 6th Order Stream feature lines in km within the reporting unit.',
        'STRMKM7': 'The total length of 7th Order Stream feature lines in km within the reporting unit.',
        'STRMKM8': 'The total length of 8th Order Stream feature lines in km within the reporting unit.',
        'STRMKM9': 'The total length of 9th Order Stream feature lines in km within the reporting unit.',
    
    #Road Density Metrics, (more classes can be added following the format if needed)
        'Shape_Length': 'Reporting Unit Shape Length', 
        'Shape_Area': 'Reporting Unit Shape Area', 
        'AREAKM2': 'The area of the reporting unit in km^2', 
        'RDKM': 'The total length of Road feature lines in km within the reporting unit.', 
        'RDDENS':'The density of Road feature lines in km/km^2 within the reporting unit.', 
        'RDTIA': ("An estimate of percent impervious area within the reporting unit."
                                "This metric uses road density as the independent variable in a linear regression model to estimate percent impervious surface (see May, et al., 1997)." 
                                "Due to the nature of the regression equation used, values below 1.8 km/km^2 are assigned a value of 0 for the percent impervious metric, while values above 11 km/km^2 are considered invalid and are reported as −1."), 
        'RDDENS0': 'The density of class 0 Road feature lines in km/km^2 within the reporting unit.',
        'RDDENS1': 'The density of class 1 Road feature lines in km/km^2 within the reporting unit.', 
        'RDDENS2': 'The density of class 2 Road feature lines in km/km^2 within the reporting unit.',  
        'RDDENS3': 'The density of class 3 Road feature lines in km/km^2 within the reporting unit.',
        'RDDENS4': 'The density of class 4 Road feature lines in km/km^2 within the reporting unit.',
        'RDDENS5': 'The density of class 5 Road feature lines in km/km^2 within the reporting unit.',                    
        'RDDENS6': 'The density of class 6 Road feature lines in km/km^2 within the reporting unit.',
        'RDDENS7': 'The density of class 7 Road feature lines in km/km^2 within the reporting unit.',
        'RDKM0': 'The total length of class 0 Road feature lines in km within the reporting unit', 
        'RDKM1': 'The total length of class 1 Road feature lines in km within the reporting unit', 
        'RDKM2': 'The total length of class 2 Road feature lines in km within the reporting unit', 
        'RDKM3': 'The total length of class 3 Road feature lines in km within the reporting unit', 
        'RDKM4': 'The total length of class 4 Road feature lines in km within the reporting unit', 
        'RDKM5': 'The total length of class 5 Road feature lines in km within the reporting unit', 
        'RDKM6': 'The total length of class 6 Road feature lines in km within the reporting unit', 
        'RDKM7': 'The total length of class 7 Road feature lines in km within the reporting unit', 
        'RDTIA1': ("An estimate of percent impervious area within the reporting unit."
                                "This metric uses class 1 road density as the independent variable in a linear regression model to estimate percent impervious surface (see May, et al., 1997)." 
                                "Due to the nature of the regression equation used, values below 1.8 km/km^2 are assigned a value of 0 for the percent impervious metric, while values above 11 km/km^2 are considered invalid and are reported as −1."),
        'RDTIA2': ("An estimate of percent impervious area within the reporting unit."
                                "This metric uses class 2 road density as the independent variable in a linear regression model to estimate percent impervious surface (see May, et al., 1997)." 
                                "Due to the nature of the regression equation used, values below 1.8 km/km^2 are assigned a value of 0 for the percent impervious metric, while values above 11 km/km^2 are considered invalid and are reported as −1."),
        'RDTIA3': ("An estimate of percent impervious area within the reporting unit."
                                "This metric uses class 3 road density as the independent variable in a linear regression model to estimate percent impervious surface (see May, et al., 1997)." 
                                "Due to the nature of the regression equation used, values below 1.8 km/km^2 are assigned a value of 0 for the percent impervious metric, while values above 11 km/km^2 are considered invalid and are reported as −1."), 
        'RDTIA4': ("An estimate of percent impervious area within the reporting unit."
                                "This metric uses class 4 road density as the independent variable in a linear regression model to estimate percent impervious surface (see May, et al., 1997)." 
                                "Due to the nature of the regression equation used, values below 1.8 km/km^2 are assigned a value of 0 for the percent impervious metric, while values above 11 km/km^2 are considered invalid and are reported as −1."), 
        'RDTIA5': ("An estimate of percent impervious area within the reporting unit."
                                "This metric uses class 5 road density as the independent variable in a linear regression model to estimate percent impervious surface (see May, et al., 1997)." 
                                "Due to the nature of the regression equation used, values below 1.8 km/km^2 are assigned a value of 0 for the percent impervious metric, while values above 11 km/km^2 are considered invalid and are reported as −1."), 
        'RDTIA6': ("An estimate of percent impervious area within the reporting unit."
                                "This metric uses class 6 road density as the independent variable in a linear regression model to estimate percent impervious surface (see May, et al., 1997)." 
                                "Due to the nature of the regression equation used, values below 1.8 km/km^2 are assigned a value of 0 for the percent impervious metric, while values above 11 km/km^2 are considered invalid and are reported as −1."), 
        'RDTIA7': ("An estimate of percent impervious area within the reporting unit."
                                "This metric uses class 7 road density as the independent variable in a linear regression model to estimate percent impervious surface (see May, et al., 1997)." 
                                "Due to the nature of the regression equation used, values below 1.8 km/km^2 are assigned a value of 0 for the percent impervious metric, while values above 11 km/km^2 are considered invalid and are reported as −1."),
        'RDTIA8': ("An estimate of percent impervious area within the reporting unit."
                                "This metric uses class 8 road density as the independent variable in a linear regression model to estimate percent impervious surface (see May, et al., 1997)." 
                                "Due to the nature of the regression equation used, values below 1.8 km/km^2 are assigned a value of 0 for the percent impervious metric, while values above 11 km/km^2 are considered invalid and are reported as −1."),

    # Population in Floodplain Metrics
        'RU_POP': 'The population for the reporting unit.',
        'FP_POP_C': 'The population in a floodplain for the reporting unit.',

    #Land Cover Proportions
        'NINDEX': 'The percent of the reporting unit occupied by All Natural Land Use.', 
        'pwtr': 'The percent of the reporting unit occupied by Water.', 
        'pbar': 'The percent of the reporting unit occupied by Barren.', 
        'pfor': 'The percent of the reporting unit occupied by Forest.', 
        'ptun': 'The percent of the reporting unit occupied by Tundra', 
        'pshb': 'The percent of the reporting unit occupied by Shrubland.', 
        'phrb': 'The percent of the reporting unit occupied by Herbaceous.', 
        'pwtl': 'The percent of the reporting unit occupied by Wetland.', 
        'pwtlw': 'The percent of the reporting unit occupied by Woody Wetland.', 
        'pwtle': 'The percent of the reporting unit occupied by Emergent Wetland.', 
        'UINDEX': 'The percent of the reporting unit occupied by All Human Land Use.', 
        'pdev': 'The percent of the reporting unit occupied by Developed.', 
        'pdevo': 'The percent of the reporting unit occupied by Open Space Developed.',
        'pdevl': 'The percent of the reporting unit occupied by Low Intensity Developed.',
        'pdevm': 'The percent of the reporting unit occupied by Medium Intensity Developed.',
        'pdevh': 'The percent of the reporting unit occupied by High Intensity Developed.', 
        'pagr': 'The percent of the reporting unit occupied by Agriculture.',
        'pagrp': 'The percent of the reporting unit occupied Pasture/Hay.', 
        'pagrc': 'The percent of the reporting unit occupied by Forest Cultivated Crop.', 

    #Neighborhood Proportions
        'NI_Prox': 'Percent All Natural Land Use within a {num} cell neighborhood', 
        'wtr_Prox': 'Percent Water within a {num} cell neighborhood', 
        'bar_Prox': 'Percent Barren within a {num} cell neighborhood', 
        'for_Prox': 'Percent Forest within a {num} cell neighborhood', 
        'tun_Prox': 'Percent Tundra within a {num} cell neighborhood', 
        'shb_Prox': 'Percent Shrubland within a {num} cell neighborhood', 
        'hrb_Prox': 'Percent Herbaceous within a {num} cell neighborhood', 
        'wtl_Prox': 'Percent Wetland within a {num} cell neighborhood', 
        'wtlw_Prox': 'Percent Woody Wetland within a {num} cell neighborhood',
        'wtle_Prox': 'Percent Emergent Wetland within a {num} cell neighborhood',
        'UI_Prox': 'Percent All Human Land Use within a {num} cell neighborhood',
        'dev_Prox': 'Percent Developed within a {num} cell neighborhood', 
        'devo_Prox': 'Percent Open Space Developed within a {num} cell neighborhood', 
        'devl_Prox': 'Percent Low Intensity Developed within a {num} cell neighborhood',
        'devm_Prox': 'Percent Medium Intensity Developed within a {num} cell neighborhood',
        'devh_Prox': 'Percent High Intensity Developed within a {num} cell neighborhood',
        'agr_Prox': 'Percent Agriculture within a {num} cell neighborhood',
        'argp_Prox': 'Percent Pasture/Hay within a {num} cell neighborhood',
        'agrc_Prox': 'Percent Cultivated Crop within a {num} cell neighborhood',

    #Select Zonal Stats
        'COUNT': 'The count of all cells in the value raster that belong to the same zone.', 
        'MIN': 'The smallest value of all cells in the value raster that belong to the same zone as the output cell will be calculated.',
        'AREA': 'The area of reporting unit feature',
        'MEAN': 'The average of all cells in the value raster that belong to the same zone as the output cell.', 
        'MAJORITY': 'The value that occurs most often for all cells in the value raster that belong to the same zone as the output cell will be calculated.', 
        'MAJORITY_COUNT': 'The frequency of all cells that contain the majority value in the value raster that belong to the same zone.',
        'MAJORITY_PERCENT': 'The percentage of cells that contain the majority value in the value raster that belong to the same zone.',
        'MAX': 'The largest value of all cells in the value raster that belong to the same zone.', 
        'MEDIAN': 'The median value of all cells in the value raster that belong to the same zone.', 
        'MINORITY': 'The value that occurs least often for all cells in the value raster that belong to the same zone as the output cell will be calculated.', 
        'MINORITY_COUNT': 'The frequency of all cells that contain the minority value in the value raster that belong to the same zone. ', 
        'MINORITY_PERCENT': 'The percentage of cells that contain the minority value in the value raster that belong to the same zone as the output cell will be calculated.',
        'PCT90': 'The percentile of all cells in the value raster that belong to the same zone as the output cell will be calculated. The 90th percentile is calculated by default.',
        'RANGE': 'The difference between the largest and smallest value of all cells in the value raster that belong to the same zone as the output cell will be calculated.', 
        'STD': 'The standard deviation of all cells in the value raster that belong to the same zone as the output cell will be calculated.', 
        'SUM': 'The total value of all cells in the value raster that belong to the same zone as the output cell will be calculated.', 
        'VARIETY': 'The number of unique values for all cells in the value raster that belong to the same zone as the output cell will be calculated.', 
        'AREA_OVER': 'The area of in value raster pixels occupying each reporting unit feature ',
}
